export const SET_GAMES = "GAMES/SET_GAMES";
export const SET_GAME_DETAIL = "GAME/SET_GAME_DETAIL";
export const SET_LOADING_FETCH = "LOADING/SET_LOADING_FETCH";
export const SET_LOADING_ADD = "LOADING/SET_LOADING_ADD";
export const SET_LOADING_EDIT = "LOADING/SET_LOADING_EDIT";
export const SET_ERROR = "ERROR/SET_ERROR";
